# THIS IS AN AUTOMATICALLY GENERATED FILE.
# DO NOT MODIFY BY HAND!!
#
# Generated by zcm-gen
#

# This file intended to be imported by user
# after setting up their LOAD_PATH,
# but you must import the type directly into the user's module:
#     pushfirst!(LOAD_PATH, "path/to/dir/containing/this/file")
#     import _encoded_t : encoded_t
module _encoded_t
__basemodule = parentmodule(_encoded_t)
__basemodule == _encoded_t && (__basemodule = Main)

import ZCM

function __init__()
end

export encoded_t
mutable struct encoded_t <: ZCM.AbstractZcmType

    # **********************
    # Members
    # **********************

    n                             ::Int32
    msg                           ::Array{UInt8,1}


    function encoded_t()

        self = new()

        # **********************
        # Members
        # **********************

        self.n = 0
        self.msg = [ 0 for dim0=1:self.n ]

        return self
    end

end

const __encoded_t_hash = Ref(Int64(0))
function ZCM._get_hash_recursive(::Type{encoded_t}, parents::Array{String})
    if __encoded_t_hash[] != 0; return __encoded_t_hash[]; end
    if "encoded_t" in parents; return 0; end
    hash::UInt64 = 0xc9386f1b86e36eb6
    hash = (hash << 1) + ((hash >>> 63) & 0x01)
    __encoded_t_hash[] = reinterpret(Int64, hash)
    return __encoded_t_hash[]
end

function ZCM.getHash(::Type{encoded_t})
    return ZCM._get_hash_recursive(encoded_t, Array{String,1}())
end

function ZCM._encode_one(msg::encoded_t, buf)
    write(buf, hton(msg.n))
    @assert size(msg.msg,1)==msg.n "Msg of type `encoded_t` requires field `msg` dimension `1` to be size `msg.n`"
    for i0=1:msg.n
        write(buf, hton(msg.msg[i0]))
    end
end

function ZCM.encode(msg::encoded_t)
    buf = IOBuffer()
    write(buf, hton(ZCM.getHash(encoded_t)))
    ZCM._encode_one(msg, buf)
    return ZCM._takebuf_array(buf);
end

function ZCM._decode_one(::Type{encoded_t}, buf)
    msg = encoded_t();
    msg.n = ntoh(reinterpret(Int32, read(buf, 4))[1])
    msg.msg = Array{UInt8, 1}(undef,msg.n)
    for i0=1:msg.n
        msg.msg[i0] = reinterpret(UInt8, read(buf, 1))[1]
    end
    return msg
end

function ZCM.decode(::Type{encoded_t}, data::Vector{UInt8})
    buf = IOBuffer(data)
    if ntoh(reinterpret(Int64, read(buf, 8))[1]) != ZCM.getHash(encoded_t)
        throw("Decode error")
    end
    return ZCM._decode_one(encoded_t, buf)
end

end # `module _encoded_t` block
