"""
THIS IS AN AUTOMATICALLY GENERATED FILE.
DO NOT MODIFY BY HAND!!
Generated by zcm-gen

This module intended to be imported by the user
after setting up their LOAD_PATH:
    pushfirst!(LOAD_PATH, "path/to/dir/containing/this/file")
    import foo

"""
module foo

__basemodule = parentmodule(foo)
__modulepath = joinpath(dirname(@__FILE__), "foo")
pushfirst!(LOAD_PATH, __modulepath)

function __init__()
end

try
    # Submodules
    include(joinpath(__modulepath, "bar.jl"))

    # Types
    include(joinpath(__modulepath, "_t1.jl"))
    include(joinpath(__modulepath, "_t2.jl"))

finally
    popfirst!(LOAD_PATH)
end

end # module foo;
