# THIS IS AN AUTOMATICALLY GENERATED FILE.
# DO NOT MODIFY BY HAND!!
#
# Generated by zcm-gen
#

begin
@assert (endswith(string(@__MODULE__), "foo")) "Only import this file through its module"

import ZCM


export t1
mutable struct t1 <: ZCM.AbstractZcmType

    # **********************
    # Members
    # **********************

    x                             ::ZCM.AbstractZcmType # foo.t2


    function t1()

        self = new()

        # **********************
        # Members
        # **********************

        self.x = __basemodule.foo.t2()

        return self
    end

end

const __foo_t1_hash = Ref(Int64(0))
function ZCM._get_hash_recursive(::Type{t1}, parents::Array{String})
    if __foo_t1_hash[] != 0; return __foo_t1_hash[]; end
    if "foo_t1" in parents; return 0; end
    newparents::Array{String} = [parents[:]; "foo_t1"::String];
    hash::UInt64 = 0x1234567802743100 + reinterpret(UInt64, ZCM._get_hash_recursive(__basemodule.foo.t2, newparents))
    hash = (hash << 1) + ((hash >>> 63) & 0x01)
    __foo_t1_hash[] = reinterpret(Int64, hash)
    return __foo_t1_hash[]
end

function ZCM.getHash(::Type{t1})
    return ZCM._get_hash_recursive(t1, Array{String,1}())
end

function ZCM._encode_one(msg::t1, buf)
    @assert isa(msg.x, __basemodule.foo.t2) "Msg of type `foo.t1` requires field `x` to be of type `foo.t2`"
    ZCM._encode_one(msg.x,buf)
end

function ZCM.encode(msg::t1)
    buf = IOBuffer()
    write(buf, hton(ZCM.getHash(t1)))
    ZCM._encode_one(msg, buf)
    return ZCM._takebuf_array(buf);
end

function ZCM._decode_one(::Type{t1}, buf)
    msg = t1();
    msg.x = ZCM._decode_one(__basemodule.foo.t2,buf)
    return msg
end

function ZCM.decode(::Type{t1}, data::Vector{UInt8})
    buf = IOBuffer(data)
    if ntoh(reinterpret(Int64, read(buf, 8))[1]) != ZCM.getHash(t1)
        throw("Decode error")
    end
    return ZCM._decode_one(t1, buf)
end

end # `begin` block
