"""
THIS IS AN AUTOMATICALLY GENERATED FILE.
DO NOT MODIFY BY HAND!!
Generated by zcm-gen

This module should only be imported by it's parent, foo

"""
module bar
@assert (endswith(string(@__MODULE__), "foo.bar")) "Only import this module through its parent"

__basemodule = parentmodule(parentmodule(bar))
__modulepath = joinpath(dirname(@__FILE__), "bar")
pushfirst!(LOAD_PATH, __modulepath)

function __init__()
    Base.eval(__basemodule, Meta.parse("import _unpackaged_t: unpackaged_t"))
end

try
    # Submodules

    # Types
    include(joinpath(__modulepath, "_t3.jl"))

finally
    popfirst!(LOAD_PATH)
end

end # module bar;
export bar
